routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Repositories\TransactionRepository;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('run-scheduler',function(){
    \Artisan::call('upesy:refresh-pending-incidents');
});
Route::get('/', function () {
    redirect('/pending-incidents');
});

app/Models/Incidents/Incident.php
<?php

namespace App\Models\Incidents;

use App\Models\Users\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Incident extends Model
{
    protected $table = 'incidents';
    
    public function partner()
    {
        return $this->belongsTo('App\Models\Partners\Partner');
    }

    public function service()
    {
        return $this->belongsTo('App\Models\Incidents\Service');
    }

    public function report()
    {
        return $this->hasOne('App\Models\Incidents\Report');
    }

    public function getProfilePicAttribute()
    {
        if (Storage::exists($this->image_url)) {
            return Storage::url($this->image_url);
        }
        return Storage::url('/img/face.png');
    }
}

app/Models/Incidents/Report.php
<?php

namespace App\Models\Incidents;

use App\Models\Partners\Partner;
use App\Models\Users\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Report extends Model
{
    use SoftDeletes;
    
    protected $table = 'reports';
    protected $appends = ['reported_on'];
    protected $guarded = ['id'];

    public function customer()
    {
        return $this->belongsTo('App\Models\Subscriptions\Customer', 'reported_by');
    }

    public function dispatchOfficer()
    {
        return $this->belongsTo(User::class, 'officer_id');
    }

    public function reportMedia()
    {
        return $this->hasMany(ReportMedia::class, 'report_id');
    }

    public function incident()
    {
        return $this->belongsTo('App\Models\Incidents\Incident');
    }

    public function reportLocations()
    {
        return $this->hasMany(ReportLocation::class);
    }

    public function getReportedOnAttribute()
    {
        $date = $this->created_at->format('dS F Y');
        $time = $this->created_at->format('g:ia');
        return $date . ' at ' . $time;
    }
}

app/Models/Incidents/ReportLocation.php
<?php

namespace App\Models\Incidents;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ReportLocation extends Model
{
    use SoftDeletes;
    
    protected $table = 'reportlocations';
}

app/Models/Incidents/ReportMedia.php
<?php

namespace App\Models\Incidents;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class ReportMedia extends Model
{
    use SoftDeletes;
    
    protected $table = 'reportMedia';

    protected $fillable = ['id'];

    protected $appends = ['report_media'];

    public function getReportMediaAttribute()
    {
        if(Storage::exists($this->name)) {
            return Storage::url($this->name);
        }
        return null;
    }
}

app/Models/Incidents/Service.php
<?php

namespace App\Models\Incidents;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Service extends Model
{
    use SoftDeletes;
    
    protected $table = 'services';

    protected $guarded = ['id'];
}

app/Http/Controllers/IncidentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ActUponIncidentRequest;
use App\Http\Requests\DispatchIncidentRequest;
use App\Repositories\IncidentRepository;
use App\Repositories\ServiceRepository;
use App\Repositories\CustomerRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Report\Repositories\ReportRepository;

class IncidentController extends Controller
{
    protected $customerRepository;
    protected $incidentRepository;
    protected $serviceRepository;
    protected $reportRepository;

    public function __construct()
    {
        $this->incidentRepository = new IncidentRepository();
        $this->customerRepository = new CustomerRepository();
        $this->serviceRepository = new ServiceRepository();
        $this->reportRepository = new ReportRepository();
    }

    public function pendingIncidents(Request $request)
    {
        $status = config('constants.reportStatus.pending');

        $data = $this->getDataForView($request, $status);

        return view('incidents.pending-incidents', [
            'incidentTypes' => $data['incidentTypes'],
            'reports' => $data['reports'],
            'reportCount' => $data['reportCount']
        ]);
    }

    public function dispatchedIncidents(Request $request)
    {
        $status = config('constants.reportStatus.dispatched');

        $data = $this->getDataForView($request, $status);

        return view('incidents.dispatched-incidents', [
            'incidentTypes' => $data['incidentTypes'],
            'reports' => $data['reports'],
            'reportCount' => $data['reportCount']
        ]);
    }

    public function resolvedIncidents(Request $request)
    {
        $status = config('constants.reportStatus.resolved');

        $data = $this->getDataForView($request, $status);

        return view('incidents.resolved-incidents', [
            'incidentTypes' => $data['incidentTypes'],
            'reports' => $data['reports'],
            'reportCount' => $data['reportCount']
        ]);
    }

    private function getDataForView($request, $status){
        
        // Check index method of the CustomerController to understand the logic here
        if ((count($request->all()) > 1) && (isset($request->searchValue))) {
            if (strpos($request->searchValue, '=')) {
                $string = $request->searchValue;
                $array = explode('=', $string);
                $request->searchValue = $array[1];
            }
        }

        $partnerId = Auth::user()->partner_id;
        $incidentTypes = $this->incidentRepository->getIncidentTypes();
        $reports = $this->incidentRepository->getIncidents($request, $status, $partnerId)['reports'];
        $reportCount = $this->incidentRepository->getIncidents($request, $status, $partnerId)['count'];

        return [
            'reports' => $reports,
            'incidentTypes' => $incidentTypes,
            'reportCount' => $reportCount
        ];
    }

    public function showPendingIncident($id, $customerId)
    {
        $incidentReport = $this->incidentRepository->show($id);
        $customer = $this->customerRepository->getCustomerById($customerId);
        $subscriptions = $this->customerRepository->getSubscriptions($customerId);
        $guardians = $this->customerRepository->getGuardians($customerId);
        $count = $this->customerRepository->getCountOfGuardians($customerId);
        $currentModeOfPayment = $this->customerRepository->getCurrentModeOfPayment($customerId);

        return view('incidents.pending-incidents-report', [
            'incidentReport' => $incidentReport,
            'customer' => $customer,
            'subscriptions' => $subscriptions,
            'guardians' => $guardians,
            'currentModeOfPayment' => $currentModeOfPayment,
            'count' => $count
        ]);
    }

    public function showDispatchedIncident($id, $customerId)
    {
        $incidentReport = $this->incidentRepository->show($id);
        $reportStatusArray = config('constants.reportStatusArray');
        $customer = $this->customerRepository->getCustomerById($customerId);
        $subscriptions = $this->customerRepository->getSubscriptions($customerId);
        $guardians = $this->customerRepository->getGuardians($customerId);
        $count = $this->customerRepository->getCountOfGuardians($customerId);
        $currentModeOfPayment = $this->customerRepository->getCurrentModeOfPayment($customerId);

        return view('incidents.dispatched-and-resolved-incidents-report', [
            'incidentReport' => $incidentReport,
            'reportStatusArray' => $reportStatusArray,
            'customer' => $customer,
            'subscriptions' => $subscriptions,
            'guardians' => $guardians,
            'currentModeOfPayment' => $currentModeOfPayment,
            'count' => $count
        ]);
    }

    public function showDispatchIncidentForm($id)
    {
        $pendingIncidentReport = $this->incidentRepository->show($id);

        return view('incidents.dispatch-incident', [
            'incidentReport' => $pendingIncidentReport
        ]);
    }

    public function dispatchIncident(DispatchIncidentRequest $request, $reportId, $customerId)
    {
        $pendingIncidentReport = $this->incidentRepository->show($reportId);

        $request['dispatched_at'] = Carbon::now();
        $request['officer_id'] = auth()->id();
        $pendingIncidentReport->update($request->all());

        return redirect()->route('pending-incident-report', [
            'report' => $reportId, 
            'customer' => $customerId
        ]);
    }

    public function showCreateIncidentReportForm($id){
        $incidentReport = $this->incidentRepository->show($id);
        $reportStatusArray = config('constants.reportStatusArray');

        return view('incidents.create-incident-report', [
            'reportStatusArray' => $reportStatusArray,
            'incidentReport' => $incidentReport
        ]);
    }

    public function actUponIncident(ActUponIncidentRequest $request, $reportId, $customerId)
    {
        $pendingIncidentReport = $this->incidentRepository->show($reportId);

        $request['acted_upon_at'] = Carbon::now();
        $pendingIncidentReport->update($request->all());

        return redirect()->route('dispatched-incident-report', [
            'report' => $reportId,
            'customer' => $customerId
        ]);
    }

    public function refreshCurrentLocation($id)
    {
        $pendingIncidentReport = $this->incidentRepository->show($id)->reportLocations()->orderBy('id', 'desc')->first();

        return response()->json(['data' => $pendingIncidentReport]);
    }

    public function refreshPendingIncidents($id)
    {
        return $this->incidentRepository->refreshPendingIncidents($id);
    }
}

resources/views/incidents/create-incident-report.blade.php
@extends('platform::dashboard')

@section('title', 'Create Incident Report')

@section('content')
    <div class="container">
        {!! Form::open(['route' => ['incident-act-upon', 
        'report' => $incidentReport->id, 
        'customer' => $incidentReport->customer->id]]) !!}

        <div class="row my-2">
            <div class="col-2">
                {!! Form::label('status', 'Report Status') !!}
            </div>
            <div class="col-6">
                {!! Form::select('status', $reportStatusArray, '', ['class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-2">
                {!! Form::label('report', 'Brief Report') !!}
            </div>
            <div class="col-6">
                {!! Form::textarea('report', null, ['placeholder' => 'Brief Report', 'class' => 'w-100 form__textarea', 'required']) !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-4 offset-8">
                <a href="javascript:history.back()">
                    <button type="button"
                        class="btn full-page-form__button full-page-form__button--back-border px-4 d-inline-block"
                        data-dismiss="modal">Back</button>
                </a>
                <button type="submit"
                    class="btn full-page-form__button d-inline-block full-page-form__button--save-color px-4">Create
                    Report</button>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
    </div>
    </div>
@stop

resources/views/incidents/dispatched-incidents.blade.php
@extends('platform::dashboard')

@section('content')
    <h1 class="ml-5 mb-3 font-thin h3 text-black">Dispatched Incidents</h1>
    <div class="white-background ml-5 mr-5 pb-3 mb-3">
        <form action="/dispatched-incidents">
            <div class="ml-3-pc pt-5">
                <div id="dispatched_incidents_table_map" class="incident-map--margin incident-map--height mb-5"></div>

                <label for="dispatched_incidents_filter_incident_type">Incident Type</label>
                <select class="d-inline-block custom-select" id="dispatched_incidents_filter_incident_type"
                    name="filter_incident_type">
                    <option value="">Select</option>
                    @foreach ($incidentTypes as $incidentType)
                        <option value="{{ $incidentType->id }}">{{ $incidentType->name }}</option>
                    @endforeach
                </select>

                <label for="dispatched_incidents_filter_start_date" class="m-l-2-4">Start Date</label>
                <input type="date" class="form-control custom-select date-select" placeholder="Start Date"
                    aria-label="Start Date" aria-describedby="basic-addon1" name="filter_start_date"
                    id="dispatched_incidents_filter_start_date">

                <label for="dispatched_incidents_filter_end_date" class="m-l-2-4">End Date</label>
                <input type="date" class="form-control custom-select date-select" placeholder="End Date"
                    aria-label="End Date" aria-describedby="basic-addon1" name="filter_end_date"
                    id="dispatched_incidents_filter_end_date">

                <button type="submit" id="dispatched_incidents_filter" class="btn filter-button d-inline-block ml-3">
                    Filter
                </button>
                <button onclick="clearFilters()" id="dispatched_incidents_reset"
                    class="btn reset-button d-inline-block ml-3">Reset
                </button>
            </div>
        </form>
        <div class="row">
            <div class="col-6 offset-6">
                <form action="/dispatched-incidents" class="ml-5 incidents-table__search-form">
                    <label for="">Search</label>
                    <input class="form-control form__table-search--border" type="text" name="searchValue"
                        aria-label="Search">
                </form>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped w-95 mx-auto mt-3" id="dispatched-incidents-table">
                <thead class="table-head-color text-left">
                    <tr>
                        <th scope="col" class="w-10">PROFILE PIC</th>
                        <th scope="col" class="w-15">INCIDENT TYPE</th>
                        <th scope="col" class="w-20">NAME</th>
                        <th scope="col" class="w-20">REPORTED ON</th>
                        <th scope="col" class="w-15">USER PHONE</th>
                        <th scope="col" class="text-center w-10">VIEW ON MAP</th>
                        <th scope="col" class="text-center">OPEN</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                        <tr>
                            <td class="text-center"><img src="{!!  $report->customer->profile_pic !!}" alt=""
                                    class="small-table__image rounded-circle"></td>
                            <td>{!! $report->incident->name !!}</td>
                            <td>{!! $report->customer->fullName !!}</td>
                            <td>{!! $report->reported_on !!}</td>
                            <td>{!! $report->customer->phone !!}</td>
                            <td class="text-center">
                                @if ($report
            ->reportLocations()
            ->orderBy('id', 'desc')
            ->first() == null ||
        $report
            ->reportLocations()
            ->latest()
            ->first() == null)
                                    <i onclick="customerHasNoKnownAddress()"
                                        class="fas fa-exclamation-triangle blue-font text-center" aria-hidden="true"></i>
                                @else
                                    <i onclick="initialize('{{ $report->reportLocations()->orderBy('id', 'desc')->first()->lat }}' , '{{ $report->reportLocations()->latest()->first()->long }}')"
                                        class="fas fa-map-marker blue-font text-center" aria-hidden="true"></i>
                                @endif
                            </td>
                            <td class="text-center">
                                <a
                                    href="{{ url('dispatched-and-resolved-incidents/' . $report->id . '/report/customer/' . $report->reported_by) }}"><i
                                        class="fas fa-eye blue-font"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <span class="ml-5">Showing 1 - 10 of {{ $reportCount }} incident reports</span>

            {{ $reports->links() }}
        </div>
    </div>
@stop

@section('pageSpecificScripts')
    <script>
        initialize(-1.286389, 36.817223)

        function customerHasNoKnownAddress() {
            alert('Customer has no known address')
        }

        function initialize(lat, long) {
            var latlng = new google.maps.LatLng(lat, long);
            var map = new google.maps.Map(document.getElementById('dispatched_incidents_table_map'), {
                center: latlng,
                zoom: 17
            });
            var marker = new google.maps.Marker({
                map: map,
                position: latlng,
                draggable: false,
                anchorPoint: new google.maps.Point(0, -29)
            });
            var infowindow = new google.maps.InfoWindow();
            google.maps.event.addListener(marker, 'click', function() {
                var iwContent = '<div id="iw_container">' +
                    '<div class="iw_title"><b>Location</b> : Noida</div></div>';
                // including content to the infowindow
                infowindow.setContent(iwContent);
                // opening the infowindow in the current map and at the current marker location
                infowindow.open(map, marker);
            });
        }

    </script>
    <script>
        clearFilters = () => {
            let href = '/dispatched-incidents'
            window.href = href
        }

    </script>
    <script>
        function checkWhetherTheTableContainsSearchResults() {
            let search = location.search.substring(1)
            searchInputElement = document.getElementById('customers-search-hidden-input');

            if (search != '') {
                searchInputElement.setAttribute('value', search);
            }
        }

    </script>
@endsection

resources/views/incidents/pending-incidents.blade.php
@extends('platform::dashboard')

@section('content')
    <h1 class="ml-5 mb-3 font-thin h3 text-black">Pending Incidents</h1>
    <div class="white-background ml-5 mr-5 pb-3 mb-3">
        <form action="/pending-incidents">
            <div class="ml-3-pc pt-5">
                <div id="pending_incidents_table_map" class="incident-map--margin incident-map--height mb-5"></div>

                <label for="pending_filter_incident_type">Incident Type</label>
                <select class="d-inline-block custom-select" id="pending_incidents_filter_incident_type"
                    name="filter_incident_type">
                    <option value="">Incident</option>
                    @foreach ($incidentTypes as $incidentType)
                        <option value="{{ $incidentType->id }}">{{ $incidentType->name }}</option>
                    @endforeach
                </select>

                <label for="pending_incidents_filter_start_date" class="m-l-2-4">Start Date</label>
                <input type="date" class="form-control custom-select date-select" placeholder="Start Date"
                    aria-label="Start Date" aria-describedby="basic-addon1" name="filter_start_date"
                    id="pending_incidents_filter_start_date">

                <label for="pending_incidents_filter_end_date" class="m-l-2-4">End Date</label>
                <input type="date" class="form-control custom-select date-select" placeholder="End Date"
                    aria-label="End Date" aria-describedby="basic-addon1" name="filter_end_date"
                    id="pending_incidents_filter_end_date">
                <button type="submit" id="pending_incidents_filter"
                    class="btn filter-button d-inline-block ml-3">Filter</button>
                <button id="pending_incidents_reset" onclick="clearFilters()"
                    class="btn reset-button d-inline-block ml-3">Reset</button>
            </div>
        </form>
        <div class="row">
            <div class="col-6 offset-6">
                <form action="/pending-incidents" class="ml-5 incidents-table__search-form">
                    <label for="">Search</label>
                    <input class="form-control form__table-search--border" type="text" name="searchValue"
                        aria-label="Search">
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table w-95 mx-auto mt-3" id="pending-incidents-table">
                <thead class="table-head-color text-left">
                    <tr>
                        <th class="d-none"></th>
                        <th scope="col" class="w-10">PROFILE PIC</th>
                        <th scope="col" class="w-15">INCIDENT TYPE</th>
                        <th scope="col" class="w-20">NAME</th>
                        <th scope="col" class="w-20">REPORTED ON</th>
                        <th scope="col" class="w-15">USER PHONE</th>
                        <th scope="col" class="text-center w-10">VIEW ON MAP</th>
                        <th scope="col" class="text-center">OPEN</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                        <tr>
                            <td class="d-none" id="pending-report-id">{!! $report->id !!}</td>
                            <td class="text-center"><img src="{!!  $report->customer->profile_pic !!}" alt=""
                                    class="small-table__image rounded-circle"></td>
                            <td>{!! $report->incident->name !!}</td>
                            <td>{!! $report->customer->fullName !!}</td>
                            <td>{!! $report->reported_on !!}</td>
                            <td>{!! $report->customer->phone !!}</td>
                            <td class="text-center">
                                @if ($report
            ->reportLocations()
            ->orderBy('id', 'desc')
            ->first() == null)
                                    <i onclick="customerHasNoKnownAddress()"
                                        class="fas fa-exclamation-triangle blue-font text-center" aria-hidden="true"></i>
                                @else
                                    <i onclick="initialize('{{ $report->reportLocations()->orderBy('id', 'desc')->first()->lat }}' , '{{ $report->reportLocations()->latest()->first()->long }}')"
                                        class="fas fa-map-marker blue-font text-center" aria-hidden="true"></i>
                                @endif
                            </td>
                            <td class="text-center">
                                <a
                                    href="{{ url('pending-incidents/' . $report->id . '/report/customer/' . $report->reported_by) }}"><i
                                        class="fas fa-eye blue-font"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <span class="ml-5">Showing 1 - 10 of {{ $reportCount }} incident reports</span>

            {{ $reports->links() }}
        </div>
    @stop

    @section('pageSpecificScripts')
        <script>
            initialize(-1.286389, 36.817223)

            function customerHasNoKnownAddress() {
                alert('Customer has no known address')
            }

            function initialize(lat, long) {
                var latlng = new google.maps.LatLng(lat, long);
                var map = new google.maps.Map(document.getElementById('pending_incidents_table_map'), {
                    center: latlng,
                    zoom: 17
                });
                var marker = new google.maps.Marker({
                    map: map,
                    position: latlng,
                    draggable: false,
                    anchorPoint: new google.maps.Point(0, -29)
                });
                var infowindow = new google.maps.InfoWindow();
                google.maps.event.addListener(marker, 'click', function() {
                    var iwContent = '<div id="iw_container">' +
                        '<div class="iw_title"><b>Location</b> : Noida</div></div>';
                    // including content to the infowindow
                    infowindow.setContent(iwContent);
                    // opening the infowindow in the current map and at the current marker location
                    infowindow.open(map, marker);
                });
            }

        </script>
        <script>
            clearFilters = () => {
                let href = '/pending-incidents'
                window.href = href
            }

        </script>
        <script>
            function checkWhetherTheTableContainsSearchResults() {
                let search = location.search.substring(1)
                searchInputElement = document.getElementById('customers-search-hidden-input');

                if (search != '') {
                    searchInputElement.setAttribute('value', search);
                }
            }

        </script>
        <script>
            let reportId = null;
            (function refreshPendingIncidents() {
                if($("#pending-incidents-table tbody tr td").first().html()) {
                    reportId = $("#pending-incidents-table tbody tr td").first().html()
                }
                    $.ajax({
                        url: '/pending-incidents/refresh/' + reportId,
                        success: function(data) {
                            if (data['incident']) {
                                let firstOption = null,
                                    secondOption;
                                toastr.options.timeOut = 0;
                                toastr.options.extendedTimeOut = 0;
                                if (data['location']) {
                                    firstOption =
                                        `<i onclick="initialize(${data['location'].lat} , ${data['location'].long})" class="fas fa-map-marker blue-font text-center" aria-hidden="true"></i>`;

                                }
                                secondOption =
                                    `<i onclick="customerHasNoKnownAddress()" class="fas fa-exclamation-triangle blue-font text-center" aria-hidden="true"></i>`;
                                toastr["error"]('', 'New Pending Incident Received')
                                $("#pending-incidents-table tbody").prepend(`<tr>
                                                                        <td class="d-none" id="pending-report-id">${data['incident'].id}</td>
                                                                        <td class="text-center"><img src="${data['incident'].customer.profile_pic}" class="small-table__image rounded-circle"></td>
                                                                        <td>${data['incident'].incident.name}</td>
                                                                        <td>${data['incident'].customer.fullName}</td>
                                                                        <td>${data['incident'].reported_on}</td>
                                                                        <td>${data['incident'].customer.phone}</td>
                                                                        <td class="text-center">
                                                                        ${data['location'] ? firstOption : secondOption}
                                                                        </td>
                                                                        <td class="text-center">
                                                                            <a href="/pending-incidents/${data['incident'].id}/report/customer/${data['incident'].reported_by}">
                                                                                <i class="fas fa-eye blue-font"></i>
                                                                            </a>
                                                                        </td>
                                                                        </tr>`);
                            }
                        },
                        complete: function() {
                            setTimeout(refreshPendingIncidents, 5000);
                        },
                        error: function (request, status, error) {
                            console.log('test', error);
                        }
                    });

            })();

        </script>
    @endsection
</div>