routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Repositories\TransactionRepository;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::any('run-scheduler',function(){
    \Artisan::call('upesy:refresh-pending-incidents');
});
Route::get('/', function () {
    redirect('/pending-incidents');
});

app/Models/Partners/AppKey.php
<?php

namespace App\Models\Partners;

use Illuminate\Database\Eloquent\Model;

class AppKey extends Model
{
    public $timestamps = false;
    
    protected $fillable = [
        'secret_key',
        'partner_id',
        'app_name',
        'channel'
    ];

    protected $table = 'appkeys';
}

app/Models/Partners/Package.php
<?php

namespace App\Models\Partners;

use App\Models\Subscriptions\Packages\PackagePricing;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Package extends Model
{
    use SoftDeletes;

    protected $table = 'packages';
    protected $guarded = ['id'];

    public function service()
    {
        return $this->belongsTo('App\Models\Incidents\Service');
    }
}

app/Models/Partners/Partner.php
<?php

namespace App\Models\Partners;

use App\Models\Incidents\Report;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Orchid\Screen\AsSource;
use Illuminate\Support\Facades\Storage;

class Partner extends Model
{
    use AsSource, SoftDeletes;

    protected $fillable = [
        'name',
        'physical_address',
        'postal_address',
        'postal_code',
        'city',
        'bank_name',
        'account_name',
        'account_number',
        'type',
        'image_id',
        'sms_balance',
        'sms_status',
        'image_url',
        'phone',
        'code',
        'partner_id',
        'status'
    ];

    protected $table = 'partners';
    protected $appends = ['image'];

    public function getTypeTitleAttribute()
    {
        return ucwords($this->type);
    }

    public function standardPartner()
    {
        return $this->hasOne('App\Models\Users\Partner', 'partner_id');
    }

    public function users()
    {
        return $this->hasMany('App\Models\Users\User');
    }

    public function packages()
    {
        return $this->hasMany('App\Models\Partners\Package');
    }

    public function services()
    {
        return $this->belongsToMany('App\Models\Incidents\Service', 'partnerServices', 'partner_id', 'service_id');
    }

    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    public function getImageAttribute(){
        if (Storage::exists($this->image_url)) {
            return Storage::url($this->image_url);
        }
        return Storage::url('/img/face.png');
    }
}

app/Models/Users/User.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Orchid\Platform\Models\User as Authenticatable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    use Notifiable, SoftDeletes;

    protected $guarded = [
        'id'
    ];

    protected $appends = ['member_since', 'fullName', 'profile_pic'];
    protected $table = 'users';

    protected $fillable = [
        'partner_id',
        'firstName',
        'lastName',
        'email',
        'phone',
        'role',
        'id_number',
        'password',
        'permissions',
        'last_login'
    ];
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

//    /**
//     * The attributes that should be cast to native types.
//     *
//     * @var array
//     */
//    protected $casts = [
//        'permissions'       => 'array',
//        'email_verified_at' => 'datetime',
//        'last_login'        => 'datetime',
//    ];
//
//    /**
//     * The attributes for which you can use filters in url.
//     *
//     * @var array
//     */
//    protected $allowedFilters = [
//        'id',
//        'name',
//        'email',
//        'permissions',
//    ];
//
//    /**
//     * The attributes for which can use sort in url.
//     *
//     * @var array
//     */
//    protected $allowedSorts = [
//        'id',
//        'name',
//        'email',
//        'last_login',
//        'updated_at',
//        'created_at',
//    ];

    public function getFullNameAttribute()
    {
        return ucwords(strtolower($this->firstName)).' '.ucwords(strtolower($this->lastName));
    }

    public function getMemberSinceAttribute()
    {
        $date = $this->created_at->format('dS M Y');
        return $date;
    }

    public function partner()
    {
        return $this->belongsTo('App\Models\Partners\Partner', 'partner_id');
    }

    public function getProfilePicAttribute()
    {
        if (Storage::exists($this->image_url)) {
            return Storage::url($this->image_url);
        }
        return Storage::url('/img/face.png');
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BankDetailsRequest;
use App\Http\Requests\PartnerRequest;
use App\Models\Partners\AppKey;
use App\Models\Partners\Partner;
use App\Models\Users\User;
use App\Repositories\PartnerRepository;
use App\Repositories\ServiceRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class PartnerController extends Controller
{
    protected $partnerRepository;
    protected $userRepository;
    protected $serviceRepository;

    public function __construct()
    {
        $this->partnerRepository = new  PartnerRepository();
        $this->userRepository = new  UserRepository();
        $this->serviceRepository = new  ServiceRepository();
    }

    public function index()
    {
        $partners = $this->partnerRepository->getAllPartners();
        $count = $this->partnerRepository->getCountOfAllPartners();

        return view('partners.index', [
            'partners' => $partners,
            'count' => $count
        ]);
    }

    public function show($id)
    {
        $partner = $this->partnerRepository->getPartnerById($id);
        $partnerUsers = $this->partnerRepository->takeFivePartnerUsers($id);
        $partnerPackages = $this->partnerRepository->takeFivePartnerPackages($id);
        $roles = ['' => 'Select Role'] + $this->userRepository->getAllDistinctRolesArrayWithoutSuperAdmin();

        return view('partners.details', [
            'partnerUsers' => $partnerUsers,
            'partner' => $partner,
            'roles' => $roles,
            'partnerPackages' => $partnerPackages
        ]);
    }

    public function users($id)
    {
        $partner = $this->partnerRepository->getPartnerById($id);
        $partnerUsers = $this->partnerRepository->getPaginatedPartnerUsers($id);
        $count = $this->partnerRepository->getCountOfPartnerUsers($id);

        return view('partners.users', [
            'partnerUsers' => $partnerUsers,
            'partner' => $partner,
            'count' => $count
        ]);
    }

    public function deactivateOrReactivate($id)
    {
        // 0 is inactive; 1 is active
        $partner = $this->partnerRepository->getPartnerById($id);

        if ($partner->status == 1) {
            $partner->update([
                'status' => 0
            ]);
        } else {
            $partner->update([
                'status' => 1
            ]);
        }

        return redirect()->route('partners');
    }

    public function showEditBankDetails($id)
    {
        $partner = $this->partnerRepository->getPartnerById($id);

        return view('partners.edit-bank-details', [
            'partner' => $partner
        ]);
    }

    public function bankStore(BankDetailsRequest $request, $id)
    {
        $partner = $this->partnerRepository->getPartnerById($id);
        $partner->update($request->all());

        return redirect()->route('partner.details', $id);
    }

    public function create()
    {
        $services = ['' => 'Select Service(s)'] + $this->serviceRepository->getAllServicesArray();
        $premiumPartners = ['' => 'Select Type'] +
            [0 => 'This is a premium partner'] +
            $this->partnerRepository->getAllPremiumPartnersArray();

        return view('partners.create', [
            'services' => $services,
            'premiumPartners' => $premiumPartners
        ]);
    }

    public function store(Request $request)
    {
        $partnerInput = $request->except('services', 'firstName', 'lastName', 'phone', 'email', 'id_number');
        $partnerInput['role'] = null;

        if ($request->get('partner_id') == 0) {
            $partnerInput['type'] = 'Premium';
            $partnerInput['partner_id'] = null;
        } else {
            $partnerInput['type'] = 'Standard';
            $partnerInput['partner_id'] = $request->get('partner_id');
        }

        if ($request->get('firstname') && $request->get('lastname')) {
            $partnerInput['role'] = 'Contact Person';
        }

        $partner = Partner::create($partnerInput);

        if ($partner->role) {
            $userInput = $request->only(['firstName', 'lastName', 'phone', 'email', 'id_number', 'role']);
            $userInput['partner_id'] = $partner->id;
            User::create($userInput);
        }

        $appKeyInputIos['partner_id'] = $partner->id;
        $appKeyInputIos['app_name'] = $request->get('name');
        $appKeyInputIos['secret_key'] = uniqid() . Str::random(19);
        $appKeyInputIos['channel'] = 'ios';

        $appKeyInputAndroid['partner_id'] = $partner->id;
        $appKeyInputAndroid['app_name'] = $request->get('name');
        $appKeyInputAndroid['secret_key'] = uniqid() . Str::random(19);
        $appKeyInputAndroid['channel'] = 'android';

        AppKey::create($appKeyInputIos);
        AppKey::create($appKeyInputAndroid);

        $partner = $this->partnerRepository->getPartnerById($partner->id);
        $partner->services()->attach($request->get('services'));

        return redirect()->route('partners');
    }
}

resources/views/partners/create-user.blade.php
@extends('platform::dashboard')

@section('title', 'Create User')

@section('content')
    <div class="container">

        {!! Form::open(['route' => ['partner.user.store', $partner->id]]) !!}

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('firstName', 'First Name') !!}
            </div>
            <div class="col-6">
                {!! Form::text('firstName', null, ['placeholder' => 'John', 'class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('lastName', 'Last Name') !!}
            </div>
            <div class="col-6">
                {!! Form::text('lastName', null, ['placeholder' => 'Doe', 'class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('phone', 'Phone Number') !!}
            </div>
            <div class="col-6">
                {!! Form::text('phone', null, ['placeholder' => '+2547xxxxxxx/07xxxxxxxx', 'class' => 'w-100 form__input', 'required'])
                !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('id_number', 'ID/Passport Number') !!}
            </div>
            <div class="col-6">
                {!! Form::text('id_number', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('password', 'Password') !!}
            </div>
            <div class="col-6">
                {!! Form::password('password', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('email', 'Email Address') !!}
            </div>
            <div class="col-6">
                {!! Form::text('email', null, ['placeholder' => 'jdoe@email.com', 'class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-3">
                {!! Form::label('role') !!}
            </div>
            <div class="col-6">
                {!! Form::select('role', $roles, '', ['class' => 'w-100 custom-select', 'required']) !!}
            </div>
        </div>

        {!! Form::hidden('partner_id', $partner->id) !!}

        <div class="row my-2">
            <div class="col-4 offset-8">
                <a href="javascript:history.back()">
                    <button type="button"
                        class="btn full-page-form__button full-page-form__button--back-border px-4 d-inline-block"
                        data-dismiss="modal">Back</button>
                </a>
                <button type="submit"
                    class="btn full-page-form__button d-inline-block full-page-form__button--save-color px-4">
                    Create User</button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@stop

resources/views/partners/create.blade.php
@extends('platform::dashboard')

@section('title','Create Partner')

@section('content')
    {!! Form::open(['route' => ['partner.store']]) !!}
    <div class="font-1-25 px-3 mx-5 font-bold">Core Details</div>
    <div class="row px-5 mx-auto mt-3">
        <div class="col">
            <div>
                {!! Form::label('name', 'Partner Name', ['class' => 'font-bold']) !!} <span
                    class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::text('name', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
            <div>
                {!! Form::label('postal_address', 'Postal Address', ['class' => 'font-bold']) !!} <span
                    class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::text('postal_address', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
            <div>
                {!! Form::label('city', 'City', ['class' => 'font-bold']) !!} <span class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::text('city', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>
        <div class="col">
            <div>
                {!! Form::label('physical_address', 'Physical Address', ['class' => 'font-bold']) !!} <span
                    class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::text('physical_address', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
            <div>
                {!! Form::label('postal_code', 'Postal Code', ['class' => 'font-bold']) !!} <span
                    class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::text('postal_code', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
            <div>
                {!! Form::label('partner_id', 'Corresponding Premium Partner', ['class' => 'font-bold']) !!} <span
                    class="red-text font-1-25">*</span>
            </div>
            <div>
                {!! Form::select('partner_id', $premiumPartners, null, ['class' => 'custom-select']) !!}
            </div>
        </div>
    </div>
    <hr class="w-95">

    <div class="font-1-25 px-3 mx-5 font-bold">Bank Details</div>
    <div class="row px-5 mx-auto mt-3">
        <div class="col">
            <div>
                {!! Form::label('bank_name', 'Bank Name', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('bank_name', null, ['class' => 'w-100 form__input']) !!}
            </div>
            <div>
                {!! Form::label('account_number', 'Account Number', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('account_number', null, ['class' => 'w-100 form__input']) !!}
            </div>
        </div>
        <div class="col">
            <div>
                {!! Form::label('account_name', 'Account Name', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('account_name', null, ['class' => 'w-100 form__input']) !!}
            </div>
        </div>
    </div>
    <hr class="w-95">

    <div class="font-1-25 px-3 mx-5 font-bold">Contact Person</div>
    <div class="row px-5 mx-auto mt-3">
        <div class="col">
            <div>
                {!! Form::label('firstName', 'First Name', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('firstName', null, ['class' => 'w-100 form__input']) !!}
            </div>
            <div>
                {!! Form::label('phone', 'Phone', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('phone', null, ['class' => 'w-100 form__input']) !!}
            </div>
            <div>
                {!! Form::label('email', 'Email', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('email', null, ['class' => 'w-100 form__input']) !!}
            </div>
        </div>
        <div class="col">
            <div>
                {!! Form::label('lastName', 'Last Name', ['class' => 'font-bold']) !!}
            </div>
            <div>
                {!! Form::text('lastName', null, ['class' => 'w-100 form__input']) !!}
            </div>
            <div>
                {!! Form::label('id_number', 'ID/Passport Number', ['class' => 'font-bold']) !!} 
            </div>
            <div>
                {!! Form::text('id_number', null, ['class' => 'w-100 form__input']) !!}
            </div>
        </div>
    </div>
    <hr class="w-95">

    <div class="font-1-25 px-3 mx-5 font-bold">Services <span class="red-text font-1-25">*</span><span class="font-1-rem">(hold the Shift key to select multiple)</span></div>
    <div class="row px-5 mx-auto mt-3">
        <div class="col">
            {{Form::select('services[]', $services, null, ['multiple' => true, 'class' => 'custom-select'])}}
        </div>
    </div>
    <div class="float-right mr-4-0">
        {!! Form::hidden('status', 1) !!}
        {!! Form::submit('Add Partner', ['class' => 'btn full-page-form__button full-page-form__button--save-color mb-5 px-4']) !!}
    </div>
    {!! Form::close() !!}

@stop

resources/views/partners/details.blade.php
@extends('platform::dashboard')

@section('title', $partner->name)
@section('description', 'Partner Details')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                @include('partners.partials.details-panel')
                @include('partners.partials.bank-details')
                @include('partners.partials.services')
            </div>
            <div class="col-sm-4">
                @include('partners.partials.users')
            </div>
        </div>
    </div>
@stop

resources/views/partners/edit-bank-details.blade.php
@extends('platform::dashboard')

@section('title', 'Edit Bank Details')

@section('content')
    <div class="container">

        {!! Form::model($partner, ['route' => ['partner.bank.store', $partner->id]]) !!}

        <div class="row my-2">
            <div class="col-2">
                {!! Form::label('bank_name', 'First Name') !!}
            </div>
            <div class="col-6">
                {!! Form::text('bank_name', null, ['placeholder' => 'ABC Bank', 'class' => 'w-100 form__input', 'required'])
                !!}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-2">
                {!! Form::label('account_name', 'Account Name') !!}
            </div>
            <div class="col-6">
                {!! Form::text('account_name', null, ['placeholder' => 'ABCAccount', 'class' => 'w-100 form__input',
                'required']) !!}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-2">
                {!! Form::label('account_number', 'Account Number') !!}
            </div>
            <div class="col-6">
                {!! Form::text('account_number', null, ['class' => 'w-100 form__input', 'required']) !!}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-4 offset-8">
                <a href="javascript:history.back()">
                    <button type="button"
                        class="btn full-page-form__button full-page-form__button--back-border px-4 d-inline-block"
                        data-dismiss="modal">Back</button>
                </a>
                <button type="submit"
                    class="btn full-page-form__button d-inline-block full-page-form__button--save-color px-4">Update
                    Bank Details</button>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

@stop

resources/views/partners/index.blade.php
@extends('platform::dashboard')

@section('content')
    <h1 class="ml-5 mb-3 font-thin h3 text-black">Partners</h1>
    <div class="white-background ml-5 mr-5 pb-3 mb-3">
        <a href="{{ route('partner.create') }}">
            <button class="btn filters-dropdown-button ml-3-neg" type="button" data-target="#filterCustomersTable"
                data-toggle="modal">
                Create Partner
            </button>
        </a>

        <div class="table-responsive">
            <table class="table mx-auto mt-5">
                <thead class="table-head-color text-left">
                    <tr>
                        <th scope="col">NAME</th>
                        <th scope="col">TYPE</th>
                        <th scope="col">PARTNER SINCE</th>
                        <th scope="col">STATUS</th>
                        <th scope="col">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($partners as $partner)
                        <tr>
                            <td>{!! $partner->name !!}</td>
                            <td>{!! $partner->type_title !!}</td>
                            <td>{!! $partner->created_at->diffForHumans() !!}</td>
                            @if ($partner->status == 1)
                                <td>Active</td>
                            @else
                                <td>Inactive</td>
                            @endif
                            <td>
                                <a href="{{ route('partner.details', $partner->id) }}"><i class="fas fa-eye"></i></a>
                                @if ($partner->status == 1)
                                    <a href="{{ route('partner.deactivate', $partner->id) }}"><i
                                            class="fas fa-trash red-text"></i></a>
                                @else
                                    <a href="{{ route('partner.deactivate', $partner->id) }}"><i
                                            class="fas fa-undo-alt green-text"></i></a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <span class="ml-5">Showing 1 - 10 of {{ $count }} partners</span>
            {{ $partners->links() }}
        </div>
    </div>
    @stop

resources/views/partners/packages.blade.php
@extends('platform::dashboard')

@section('title', 'Packages')
@section('description', 'belonging to ' . $partner->name)

@section('content')
    <div class="white-background ml-5 mr-5 pb-3 mb-3">
        <div class="table-responsive">
            <table class="table mx-auto mt-5">
                <thead class="table-head-color text-left">
                    <tr>
                        <th scope="col">NAME</th>
                        <th scope="col">TYPE</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($packages as $package)
                        <tr>
                            <td>{!! $package->name !!}</td>
                            <td>{!! $package->service->name !!}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <span class="ml-5">Showing 1 - 10 of {{ $count }} packages</span>
            {{ $packages->links() }}
        </div>
    </div>
    @stop

resources/views/partners/users.blade.php
@extends('platform::dashboard')

@section('title', 'Users')
@section('description', 'belonging to ' . $partner->name)

@section('content')
    <div class="white-background ml-5 mr-5 pb-3 mb-3">
        <div class="table-responsive">
            <table class="table mx-auto mt-5">
                <thead class="table-head-color text-left">
                    <tr>
                        <th scope="col">NAME</th>
                        <th scope="col">CONTACT PHONE</th>
                        <th scope="col">EMAIL ADDRESS</th>
                        <th scope="col">ID/PASSPORT</th>
                        <th scope="col">ROLE</th>
                        <th scope="col">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($partnerUsers as $user)
                        <tr>
                            <td>{!! $user->full_name !!}</td>
                            <td>{!! $user->phone !!}</td>
                            <td>{!! $user->email !!}</td>
                            <td>{!! $user->id_number !!}</td>
                            <td>{!! $user->role !!}</td>
                            <td>
                                <a href="{{ route('user.profile', $user->id) }}"><i class="fas fa-eye"></i></a>
                                <a href="/partner/{{ $user->id }}/delete"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <span class="ml-5">Showing 1 - 10 of {{ $count }} users</span>
            <span class="float-right">{{ $partnerUsers->links() }}</span>
        </div>
    </div>
@stop